on:
  pull_request:
    # Target for PRs
    branches: [main]
    # Synchronize triggers the workflow when the PR is updated with new commits
    types: [opened, reopened, synchronize]

jobs:
  build-cache:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/build-cache

  use-cache:
    runs-on: ubuntu-latest
    needs: build-cache
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/restore-cache
